tags:
  - name: Event Booking
    description: Event Booking API

paths:
  # [GET] Events
  /events:
    get:
      tags:
        - events
      summary: Get all events
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

  # [POST] Booking
  /booking:
    post:
      tags:
        - bookings
      summary: Book an event
      parameters:
        - name: body
          in: body
          description: Booking Data
          required: true
          schema:
            $ref: "#/definitions/booking"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

# definitions
definitions:
  booking:
    type: object
    required:
      - event_name
      - username
      - email
      - no_of_tickets
      - eventId
    properties:
      event_name:
        type: string
        description: Event name
      username:
        type: string
        description: Register Username
      email:
        type: string
        description: Register Email
      no_of_tickets:
        type: string
        description: Number of tickets
      eventId:
        type: string
        description: event ID for reference

schemes:
  - https
  - http
